### ISSUE TITLE
spark_submit issues

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/glm-parser#30] opened 2016-06-09 06:14 UTC
problem with file permissions are causing some issues with spark_submit.

**Comment by Travelinglight** [comment] 2016-06-09 18:11
I tried changing 
`fformat = open(self.format_path)`
to
`fformat = open(self.format_path, "r")`
in src/data/datapool.py, line 174.
However, the exception still exists, permission denied again.
It's weird..

**Comment by avacariu** [comment] 2016-06-09 19:52
`open(self.format_path, "r")` and `open(self.format_path)` are exactly the same thing.

Does the user under which Spark runs have read permissions on the file (and the entire path leading to the file)?

**Comment by anoopsarkar** [comment] 2016-06-09 19:55
So when spark_submit runs the job on the hadoop cluster, the code is executed on various hadoop compute nodes. All these nodes may not have access to the source files (except for the one being executed). I remember Vivian creating an `.egg` file to deploy the entire source directory to the compute node before starting executing. Can you check for this code in the repo and see if that solves this issue?

**Comment by Travelinglight** [comment] 2016-06-09 20:20
I don't know why but `src/*.egg` is in the `.gitignore` file.
I also find there is `module.egg` in the repo I cloned before on the cluster, but it seems to be a binary file.

I want to use the config file and data in `/cs` instead of my own home directory. If that works then we find the reason of this exception. However I don't have the privilege to update the config files to the format files. How can I get the privilege to do so?

**Comment by anoopsarkar** [comment] 2016-06-09 21:15
The `.egg` file needs to be created at compile time with the binary format of the machine where it is deployed, and I assume the egg file is deployed either during or before the `spark_submit` call. @viviankou might be able to shed some light on this process.

I don't understand what you mean by "update the config files to the format files". Can you give an example of what you want to do?

**Comment by Travelinglight** [comment] 2016-06-09 21:32
The config files (specifying column names) are in `/cs` directory. I want to use those config files instead of those in my home directory.
But those config files are out-dated, and we have changed config files to format files now. I want to update them.

**Comment by anoopsarkar** [comment] 2016-06-09 21:48
In `/cs/natlang-projects/glm-parser/config`?

I can give you permissions. It will take a little bit of time (I'm sorting out the sudo issues).

**Comment by Travelinglight** [comment] 2016-06-09 21:54
yes, `/cs/natlang-projects/glm-parser` actually, because I want to place the whole `config` folder with a `format` folder

**Comment by anoopsarkar** [comment] 2016-06-09 22:34
ok. I gave group permissions to that directory and all sub-directories to the cs-natlang group. It should let you make changes now.

**Comment by Travelinglight** [comment] 2016-06-10 16:53
Using format files in `/cs/natlang-projects/glm-parser` doesn't help, permission is still denied.
Maybe the problem is in .egg file. 
@viviankou Could you tell me where this `.egg` file is from?
In the script I saw a line `mv dist/module-0.1-py2.7.egg module.egg`, but there's no `dist` folder in `src`

**Comment by viviankou** [comment] 2016-06-10 18:06
The .egg file is created by run_spark_hadoop.sh and deployed to the nodes using "--py-files module.egg". It basically contains all the binary code for the spark nodes to run and it won't cause permission problem.
Which file causing the permission problem?

**Comment by anoopsarkar** [comment] 2016-06-10 18:08
Thanks for the clarification @viviankou 

We should add this to the README file in the spark_submit section.

**Comment by anoopsarkar** [comment] 2016-06-10 18:09
Also, this means we can use the format files from inside the source directory rather than loading from a mounted filesystem like `/cs/natlang-projects`

**Comment by viviankou** [comment] 2016-06-10 18:12
I see the problem. @Travelinglight you need to use the config file in your home dir instead of /cs since you are on hadoop cluster, your user group is under hadoop hdfs and do not have the access permission to /cs. Basically you need to put all the files you need either in your home dir or on hdfs.

**Comment by anoopsarkar** [comment] 2016-06-10 18:13
If the config file is in the `.egg` file then that should also work?

**Comment by Travelinglight** [comment] 2016-06-10 18:14
Actually I used the format files in my home directory before and got this PermissionDenied exception. That's why I used the format files in /cs.
Is there any instructions of putting files on hdfs?

**Comment by viviankou** [comment] 2016-06-10 18:16
Yeah, the alternative is shipping the files required by the application to computing nodes.

**Comment by jeticg** [comment] 2016-06-25 08:02
I think we need to let the glm_parser read the configs and format files from HDFS for yarn mode. I'll try to implement this.

**Comment by jeticg** [comment] 2016-06-29 03:41
The config files if uploaded by being added to the egg file could be uploaded to HDFS, but it would require standard file system operations to access it, such as `open(config)`, which is not supported by HDFS. Also, it will be uploaded to a temporary location on HDFS, which cannot be accessed without knowing the application id, making locating the config file a bit complicated.
Since we have to upload it to HDFS anyway, it might be better to let the GlmParser read it directly directly from HDFS. I have added the support for reading configs and formats, as well as original data files on HDFS, it has been tested to be working, therefore I shall now close this issue.

**Closed by jeticg** 2016-06-29 03:41 UTC

**Comment by anoopsarkar** [comment] 2016-06-29 05:03
Just to clarify: by working, do you mean that the loading functionality of config files now works or does it mean that you finished a training run on the hadoop cluster for a few iterations using this new code?

**Comment by jeticg** [comment] 2016-06-29 05:11
I have tested my latest commit on sequential, spark standalone and spark yarn mode with default.config, the test results are exactly the same with the results I got from earlier tests on master branch. This is not the complete penn-wsj-deps dataset though, it took 30 hours to get the result on my tiny cluster last time.

**Comment by anoopsarkar** [comment] 2016-06-29 05:28
That sounds good. In general, when I see "tested to be working" I'm not sure what that means exactly. From now on, we should all assume that the new code was at least was tested by training on a few sections and testing on dev.

Is this ready for a pull request to master? We can do a code review as we discussed in the pull request.

**Comment by jeticg** [comment] 2016-06-29 05:33
I thought we might need to do a code review for every single file so I already submitted a pull request and merged it into master, it's better for me to finish everything I am working on and pause for the review than leaving half-finished work to do after the review. I tried doing the code review myself, but it took way too long so I decided to leave it until our meeting tomorrow.

**Comment by jeticg** [comment] 2016-06-29 05:39
I can't promise it to be bug free but I did all I could. Running tests on hadoop is really slow, it always took me at least 5 minutes before letting me know whether it works or not, sometimes even longer.

**Comment by jeticg** [comment] 2016-06-29 05:44
Also, spark's hadoop interface is a bit frustrating because it doesn't allow overwriting existing files, nor `isdir` or `isfile` checks, so the error messages might be a problem. Also, when parsing the filenames, when one of the regular expressions fails to return with any result the whole programmes crushes, so far if our files are placed correctly there's nothing to worry about, but in the event that the user makes any mistake, the error message would be rather difficult to handle.

**Comment by anoopsarkar** [comment] 2016-06-29 17:43
I think the correct way is to have a separate pre-processor that stages all the necessary files (training data shards, config files, etc.) on a specific hdfs directory (this stage can use regular expressions, but could do that in multiple stages, first step in Python and second step as a bash script, etc. and does not need to be integrated with the glm_parser codebase). 

Then glm_parser in spark mode just gets the hdfs directory as input and does not have to rely on regular expressions or other file system commands. The assumption is that the hdfs directory is setup correctly and glm_parser should raise an error if it is missing any files during the load to RDDs.

This way seems a lot simpler and more robust to me.
